# Definición del nombre
name: integracion continua con node.js

# Accionar el flujo de trabajo
on: 
  pull_request:
    branches: [ master ]

# Creación de nuestros trabajos
jobs:
  ci_to_master:
    # Defino bajo que "Contenedor" github va a correr el código
    runs-on: ubuntu-latest
    # Definó y ordeno los pasos que quiero ejecutar
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        # Definó el entorno en el que va a correr mi código
        with:
          node-version: 10
      # Los comandos para probar mi código    
      - run: npm ci
      - run: npm test
      - run: npm run build
